-- V1__init.sql — H2 (dev only, PostgreSQL-compatible mode)
-- Replace with your actual schema. This file is executed once at startup by Flyway.

CREATE TABLE IF NOT EXISTS example (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)  NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
